"use strict";

const http = require("http");
const fs = require("fs");
const path = require("path");

const log = require("./logger");

const PUBLIC_DIR = path.join(__dirname, "..", "public");

/**
 * Mapbox GL JS, served from this driver rather than from Mapbox's CDN.
 *
 * The page is embedded in a console on another origin, and a cross-origin
 * subresource is exactly the thing that does not survive that: privacy
 * extensions and frame-level third-party blocking stop it, and a camera
 * network may have no route to the internet at all. Serving the library from
 * here removes one origin from the equation - the tiles still come from
 * Mapbox, which is unavoidable, but a page that cannot draw a basemap can at
 * least say so instead of dying on a missing global.
 */
const MAPBOX_DIST = path.dirname(require.resolve("mapbox-gl/dist/mapbox-gl.js"));
const VENDOR = {
  "/vendor/mapbox-gl.js": path.join(MAPBOX_DIST, "mapbox-gl.js"),
  "/vendor/mapbox-gl.css": path.join(MAPBOX_DIST, "mapbox-gl.css"),
};

const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".svg": "image/svg+xml",
};

/**
 * The page's own configuration, generated rather than committed.
 *
 * The Mapbox token is a browser credential - it has to reach the browser to be
 * of any use - so it is read from the environment here and served to whoever
 * can already reach this port. It is never written into a file in the repo.
 */
function envScript(config) {
  return (
    "window.SC_MAP = " +
    JSON.stringify({
      token: config.mapboxToken,
      style: config.mapboxStyle,
      driver: `${config.driverName}/${config.driverVersion}`,
    }) +
    ";\n"
  );
}

/**
 * Serves the map page.
 *
 * It cannot live in the Smart Checkpoints server's `public/` directory: that
 * directory is wiped and regenerated by every console build. Hosting its own
 * page from its own process is the whole point of the split - the server never
 * imports a mapping library and never learns whether this is Mapbox or
 * anything else.
 */
function createHttpServer(config) {
  const server = http.createServer((req, res) => {
    const url = new URL(req.url, `http://${req.headers.host || "localhost"}`);

    if (url.pathname === "/env.js") {
      res.writeHead(200, {
        "content-type": TYPES[".js"],
        "cache-control": "no-store",
      });
      res.end(envScript(config));
      return;
    }

    if (url.pathname === "/healthz") {
      res.writeHead(200, { "content-type": "application/json" });
      res.end(JSON.stringify({ ok: true, driver: config.driverName }));
      return;
    }

    if (VENDOR[url.pathname]) {
      fs.readFile(VENDOR[url.pathname], (err, body) => {
        if (err) {
          // Reinstalling is the fix, and the page will say so on screen.
          log.error(
            `cannot read ${VENDOR[url.pathname]}: ${err.message}. ` +
              "Run npm install in this driver.",
          );
          res.writeHead(500).end("mapbox-gl is not installed");
          return;
        }
        res.writeHead(200, {
          "content-type": TYPES[path.extname(url.pathname)],
          "cache-control": "public, max-age=86400",
        });
        res.end(body);
      });
      return;
    }

    const requested = url.pathname === "/" ? "/index.html" : url.pathname;
    // Resolve inside the public directory and check that it stayed there:
    // `..` in a path is how a static server ends up serving a .env file.
    const file = path.resolve(PUBLIC_DIR, `.${requested}`);
    if (!file.startsWith(PUBLIC_DIR)) {
      res.writeHead(403).end("Forbidden");
      return;
    }

    fs.readFile(file, (err, body) => {
      if (err) {
        res.writeHead(404, { "content-type": "text/plain" }).end("Not found");
        return;
      }
      res.writeHead(200, {
        "content-type": TYPES[path.extname(file)] || "application/octet-stream",
        // The page is meant to be framed, by exactly one thing: the console
        // that approved it. Everything it renders came from that console in
        // the first place, so there is nothing here to clickjack, but there is
        // no reason for anything else to frame it either.
        "x-content-type-options": "nosniff",
      });
      res.end(body);
    });
  });

  return {
    start() {
      return new Promise((resolve) => {
        server.listen(config.port, config.host, () => {
          log.info(`serving the map page on http://${config.host}:${config.port}/`);
          resolve();
        });
      });
    },
    stop() {
      server.close();
    },
  };
}

module.exports = { createHttpServer };
